skip_tags: true
clone_depth: 20
clone_folder: c:\projects\xapian
environment:
  global:
    AUTOMATED_TESTING: 1
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
build_script:
  - bash -c 'pacman -Sy --noconfirm --needed base-devel mingw-w64-x86_64-doxygen mingw-w64-x86_64-graphviz doxygen swig zlib-devel'
  - bash -c 'time ./bootstrap xapian-core'
  - bash -c 'time ./configure'
  - bash -c 'time make -j2' < nul
test_script:
  - bash -c 'time make check VERBOSE=1' < null
