skip_tags: true
clone_depth: 20
clone_folder: c:\projects\xapian
environment:
  global:
    AUTOMATED_TESTING: 1
  matrix:
  - TOOLCHAIN: mingw64
    platform: x64
install:
  - ps: >-
      $env:CONFIGOPTS="--disable-documentation"
  - ps: >-
      $env:PATH="C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;C:\msys64\usr\bin;$env:PATH"
  - ps: >-
      $env:CONFIGOPTS+=" --host=x86_64-w64-mingw32"
  - curl https://oligarchy.co.uk/xapian/patches/unicode-data121a.cc > xapian-core\unicode\unicode-data.cc
  - bash -c 'pacman -Sy --noconfirm --needed libuuid-devel base-devel doxygen mingw-w64-x86_64-toolchain mingw-w64-x86_64-doxygen mingw-w64-x86_64-python-pip mingw-w64-x86_64-graphviz zlib-devel'
  - bash -c 'time ./bootstrap --fetch-url-command="curl -L" xapian-core xapian-bindings'
build_script:
  - bash -c 'time ./configure $CONFIGOPTS --disable-backend-honey --with-go'
  - bash -c 'time make -j2' < nul
test_script:
  - bash -c 'time make check VERBOSE=1' < nul

