dist: xenial
language: cpp
cache: ccache
notifications:
  irc: "chat.freenode.net#xapian-devel"
matrix:
  include:
    - compiler: clang
      os: linux
      # Clang is already installed, but we want to build using the
      # llvm c++ library, not the GCC one. (Otherwise, depending on
      # the GCC version, there can be issues.)
      addons:
        apt:
          packages:
            - doxygen
            - graphviz
            - help2man
            - python-docutils
            - pngcrush
            - python-sphinx
            - uuid-dev
            - libpcre3-dev
            - libmagic-dev
            - tcl
            - libsvm-dev
            - libc++-dev
            - libicu-dev
            - pkg-config
            - libpoppler-cpp-dev
            - libe-book-dev
            - libetonyek-dev
            - libtesseract-dev
            - libgmime-2.6-dev
      env: USE_CC=clang USE_CXX='clang++ -stdlib=libc++'        
before_script:
  # Bootstrap everything (including letor, which isn't done
  # by default), then configure using our chosen compiler.
  - eval "$(gimme 1.14)"
  - eval env
  - travis_retry ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  - ./configure $confargs CC="$USE_CC" CXX="$USE_CXX"
script:
  - sudo make -j2
  - $installcore
  - make -j2 check VERBOSE=1 AUTOMATED_TESTING=1
  # grep '^' passes through all input while giving a non-zero exit status if
  # that input is empty.
  - git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
