dist: xenial
language: cpp
cache: ccache
notifications:
  irc: "chat.freenode.net#xapian-devel"
matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          packages:
#             - doxygen
#             - graphviz
#             - help2man
#             - python-docutils
#             - pngcrush
#             - python-sphinx
#             - uuid-dev
#             - libpcre3-dev
#             - libmagic-dev
#             - lua5.3
#             - liblua5.3-dev
#             - mono-devel
#             - golang-go
#             - python-dev
#             - python3-dev
#             - tcl
#             - libsvm-dev
#             - libicu-dev
#             - pkg-config
#             - libpoppler-cpp-dev
#             - libe-book-dev
#             - libetonyek-dev
#             - libtesseract-dev
#             - libgmime-2.6-dev
      env: CPPFLAGS=-D_GLIBCXX_DEBUG
before_script:
  # Bootstrap everything (including letor, which isn't done
  # by default), then configure using our chosen compiler.
  - wget https://dl.google.com/go/go1.14.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.14.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - /usr/local/go/bin/go env 
  - /usr/local/go/bin/go env -w
  #- travis_retry ./bootstrap xapian-core xapian-applications/omega swig xapian-bindings xapian-letor
  #- ./configure $confargs CC="$USE_CC" CXX="$USE_CXX"
script:
  #- make -j2
  #- $installcore
  #- make -j2 check VERBOSE=1 AUTOMATED_TESTING=1
  # grep '^' passes through all input while giving a non-zero exit status if
  # that input is empty.
  #- git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
