dist: xenial
language: cpp
cache: ccache
notifications:
  irc: "chat.freenode.net#xapian-devel"
matrix:
  include:
    - compiler: clang
      os: linux
      # Clang is already installed, but we want to build using the
      # llvm c++ library, not the GCC one. (Otherwise, depending on
      # the GCC version, there can be issues.)
      env: USE_CC=clang USE_CXX='clang++ -stdlib=libc++'
script:
  - sudo -e make -j2
  - $installcore
  - make -e -j2 check VERBOSE=1 AUTOMATED_TESTING=1
  # grep '^' passes through all input while giving a non-zero exit status if
  # that input is empty.
  - git status --porcelain|grep '^' && { echo "The generated files listed above are not in .gitignore" ; exit 1; }; true
